/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Apache.Beam.Dataflow.Java.utilities;

import Apache.Beam.Dataflow.Java.list.LinkedList;

public class StringUtils {
    public static String join(LinkedList source) {
        return JoinUtils.join(source);
    }

    public static LinkedList split(String source) {
        return SplitUtils.split(source);
    }
}
